INSERT INTO omega.parametros(codigo, descripcion, valor)VALUES('OrigenFollowme', N'', N'FollowMe');
INSERT INTO omega.parametros(codigo, descripcion, valor)VALUES('OrigenRealstate', N'', N'Realstate');
INSERT INTO omega.parametros(codigo, descripcion, valor)VALUES('OrigenOcr', N'', N'Ocr');
INSERT INTO omega.parametros(codigo, descripcion, valor)VALUES('OrigenMaf', N'', N'Maf');
INSERT INTO omega.parametros(codigo, descripcion, valor)VALUES('OrigenColiving', N'', N'Coliving');
INSERT INTO omega.parametros(codigo, descripcion, valor)VALUES('selectsCuota', N'Listado de cuotas', N'[{"id":1,"description":"1"},{"id":2,"description":"2"},{"id":3,"description":"3"},{"id":4,"description":"4"},{"id":5,"description":"5"},{"id":6,"description":"6"},{"id":7,"description":"7"},{"id":8,"description":"8"},{"id":9,"description":"9"},{"id":10,"description":"10"},{"id":11,"description":"11"},{"id":12,"description":"12"},{"id":13,"description":"Anual"}]');
INSERT INTO omega.parametros(codigo, descripcion, valor)VALUES(N'selectsPercep', N'Listado de percepciones', N'[{"id":1,"description":"IVA 21%"},{"id":2,"description":"IVA 27%"}]');
INSERT INTO omega.parametros(codigo, descripcion, valor)VALUES(N'selectsPercepProv', N'Listado de percepciones', N'[{"id":1,"description":"IVA 21%"},{"id":2,"description":"IVA 27%"}]');
INSERT INTO omega.parametros(codigo, descripcion, valor)VALUES(N'selectsTarifas', N'Listado de tarifas', N'[{"id":1,"description":"T1"},{"id":2,"description":"T2"},{"id":3,"description":"T3"},{"id":4,"description":"T4"}]');
INSERT INTO omega.parametros(codigo, descripcion, valor)VALUES(N'selectsAnioCuota', N'Listado de anio cuota', N'[{"id":1,"description":"2023"},{"id":2,"description":"2024"},{"id":3,"description":"2025"},{"id":4,"description":"2026"}]');
INSERT INTO omega.parametros(codigo, descripcion, valor)VALUES(N'SitioEmpresa', NULL, N'0370');
INSERT INTO omega.parametros(codigo, descripcion, valor)VALUES(N'UsuarioSitio', N'', N'LoaderOMEGA');
INSERT INTO omega.parametros(codigo, descripcion, valor)VALUES(N'TipoDeServicio', N'', N'5');
INSERT INTO omega.parametros(codigo, descripcion, valor)VALUES(N'pathFacturaFisica', N'Ruta donde se encuentran los .pdf de las facturas procesadas por OMEGA', N'cloudwing04\RPA\pdf');